# Generated by Django 5.1.3 on 2024-11-18 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_code_course_instructor_and_more'),
        ('grades', '0002_initial'),
        ('students', '0004_rename_enrollment_date_student_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.CharField(default='Ayan Aksha', max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course')},
        ),
    ]
