# Generated by Django 5.1.3 on 2024-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Aidar', max_length=100),
        ),
    ]
