# Generated by Django 5.1.3 on 2024-11-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_end_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Ayan Aksha', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
